let products=[],cart=JSON.parse(localStorage.cart||"[]"),me=null;
const $=id=>document.getElementById(id), af=n=>new Intl.NumberFormat("fa-AF").format(n)+" افغانی";
async function api(u,o={}){let r=await fetch(u,{...o,headers:{"Content-Type":"application/json",...(o.headers||{})},credentials:"include"});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"خطا");return d}
async function loadProducts(){products=await api("/api/products");let q=($("q").value||"").toLowerCase();let a=products.filter(p=>p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));$("products").innerHTML=a.map(p=>`<div class="card"><img src="${p.image_url||'https://via.placeholder.com/500x350?text=Afghan+Shop'}"><div><h3>${p.name}</h3><p>${p.category}</p><p class="price">${af(p.price_afn)}</p><small>موجودی: ${p.stock}</small><button class="btn" onclick="add(${p.id})">افزودن به سبد</button></div></div>`).join("")}
function add(id){cart.push(id);localStorage.cart=JSON.stringify(cart);$("count").textContent=cart.length}
function openCart(){$("modal").style.display="block";let c={};cart.forEach(id=>c[id]=(c[id]||0)+1);let total=0;let h=Object.entries(c).map(([id,n])=>{let p=products.find(x=>x.id==id);if(!p)return"";total+=p.price_afn*n;return `<p>${p.name} × ${n} — ${af(p.price_afn*n)}</p>`}).join("");$("content").innerHTML=`<h2>سبد خرید</h2>${h||"<p>سبد خالی است.</p>"}<hr><b>مجموع: ${af(total)}</b><button class="btn" onclick="placeOrder()">ثبت سفارش</button>`}
async function placeOrder(){if(!cart.length)return;try{me=await api("/api/me")}catch{return openLogin();}let name=prompt("نام گیرنده"),phone=prompt("شماره تماس"),address=prompt("آدرس");if(!name||!phone||!address)return;let items=Object.entries(cart.reduce((a,id)=>(a[id]=(a[id]||0)+1,a),{})).map(([product_id,quantity])=>({product_id,quantity}));try{let o=await api("/api/orders",{method:"POST",body:JSON.stringify({items,customer_name:name,phone,address})});cart=[];localStorage.cart="[]";$("count").textContent=0;$("content").innerHTML=`<h2>سفارش #${o.id} ثبت شد</h2><p>مبلغ: ${af(o.total_afn)}</p><button class="btn" onclick="pay(${o.id})">پرداخت آنلاین</button>`}catch(e){alert(e.message)}}
async function pay(id){try{let x=await api("/api/payments/create",{method:"POST",body:JSON.stringify({order_id:id})});if(x.checkout_url)location.href=x.checkout_url}catch(e){alert(e.message)}}
function openLogin(){$("modal").style.display="block";$("content").innerHTML=`<h2>ورود</h2><div class="form"><input id="email" placeholder="ایمیل"><input id="pass" type="password" placeholder="رمز عبور"><button class="btn" onclick="login()">ورود</button><hr><h3>ثبت‌نام</h3><input id="name" placeholder="نام"><button class="btn" onclick="register()">ثبت‌نام</button></div>`}
async function login(){try{me=await api("/api/login",{method:"POST",body:JSON.stringify({email:$("email").value,password:$("pass").value})});closeModal();alert("خوش آمدید")}catch(e){alert(e.message)}}
async function register(){try{await api("/api/register",{method:"POST",body:JSON.stringify({name:$("name").value,email:$("email").value,password:$("pass").value})});closeModal();alert("حساب ساخته شد")}catch(e){alert(e.message)}}
async function openAdmin(){try{let m=await api("/api/me");if(m.role!=="admin")throw Error("شما ادمین نیستید");let d=await api("/api/admin/dashboard"),o=await api("/api/admin/orders");$("modal").style.display="block";$("content").innerHTML=`<h2>پنل مدیریت</h2><div><span class="stat">کالا: ${d.products}</span><span class="stat">سفارش: ${d.orders}</span><span class="stat">کاربران: ${d.users}</span><span class="stat">درآمد: ${af(d.revenue)}</span></div><h3>افزودن کالا</h3><div class="form"><input id="pn" placeholder="نام"><input id="pc" placeholder="دسته‌بندی"><input id="pp" type="number" placeholder="قیمت AFN"><input id="ps" type="number" placeholder="موجودی"><input id="pi" placeholder="لینک تصویر"><button class="btn" onclick="addProduct()">افزودن</button></div><h3>سفارش‌ها</h3><table><tr><th>#</th><th>مشتری</th><th>مبلغ</th><th>وضعیت</th></tr>${o.map(x=>`<tr><td>${x.id}</td><td>${x.customer_name}</td><td>${af(x.total_afn)}</td><td>${x.status}/${x.payment_status}</td></tr>`).join("")}</table>`}catch(e){alert(e.message)}}
async function addProduct(){try{await api("/api/admin/products",{method:"POST",body:JSON.stringify({name:$("pn").value,category:$("pc").value,price_afn:Number($("pp").value),stock:Number($("ps").value),image_url:$("pi").value})});alert("کالا اضافه شد");loadProducts()}catch(e){alert(e.message)}}
function closeModal(){$("modal").style.display="none"}loadProducts();$("count").textContent=cart.length;
